name = "blazenote-api"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "blazenote"
database_id = "03f478d7-587c-4261-a287-1b677a35cfb0"
migrations_dir = "./migrations"

[vars]
# MY_VAR = "my-variable"
R2_ENDPOINT = "https://e206e81b43614ccd76aed224ad5e1cbc.r2.cloudflarestorage.com/blazenote"
R2_ACCESS_KEY = "25b2a0662544ef5a8ea952c6fe8a8726"
R2_SECRET_KEY = "deecca000f189836621576cc9738ca037cc3cc6e334793eadf1ce610b2fde3f2"
R2_BUCKET_NAME = "blazenote"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "blazenote"
preview_bucket_name = "dev-blazenote"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true