name = "blazenote-backend"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = [ "nodejs_compat" ]

# TODO: In-Workshop Activities. Uncomment the code below:
 
# [[d1_databases]]
# binding = "DB"
# database_name = "blazenote"
# database_id = "<your-database-id>"
# migrations_dir = "./migrations"
# remote = true

# [[r2_buckets]]
# binding = "R2_BUCKET"
# bucket_name = "blazenote"
# preview_bucket_name = "dev-blazenote"
# remote = true

# Enable observability logging
[observability.logs]
enabled = true
